
services:
  hiddifymanager:
    build: . 
    #image: ghcr.io/hiddify/hiddify-manager:latest #latest 
    #image: ghcr.io/hiddify/hiddify-manager:beta 
    #image: ghcr.io/hiddify/hiddify-manager:dev #specific version #image: ghcr.io/hiddify/hiddify-manager:v10.80.0 ports: - "80:80" - "443:443" privileged: true cap_add: - NET_ADMIN volumes: - ./docker-data/:/opt/hiddify-manager/data/ env_file: - path: ./docker.env

    network_mode: host
    env_file:
      - path: ./docker.env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    ports:
      - "127.0.0.1:3306:3306"

    env_file:
      - path: ./docker.env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1       # Root user password
      MYSQL_DATABASE: hiddifypanel             
      MYSQL_USER: hiddifypanel                     
    volumes:
      - ./docker-data/mariadb_data:/var/lib/mysql          # Persistent storage for database files
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 5s
      retries: 10
  redis:

    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - path: ./docker.env
    command: sh -c "redis-server --requirepass \"$$REDIS_PASSWORD\""
    volumes:
      - ./docker-data/redis_data:/data                # Persistent storage for Redis data
    
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
      interval: 5s
      retries: 10